Fix unicode error (bootstrap)

diff --git a/gc/install-bdwgc-7_2alpha5-20110107 b/gc/install-bdwgc-7_2alpha5-20110107
--- a/gc/install-bdwgc-7_2alpha5-20110107
+++ b/gc/install-bdwgc-7_2alpha5-20110107
@@ -38,10 +38,10 @@ $tar xfj $src  -C ../gc || (echo "$tar xfz $src failed"; exit 1)
 mv ../gc/$gcdir "../gc/$gc" || (echo "mv $gc failed"; exit 1)
 
 # android patch
-#* (cd "../gc/$gcdir"_fth && $patch -p1 < ../$gc-android.patch > /dev/null) */
-#* if [ $? != "0" ]; then echo "android patch failed"; exit 1; fi      */
-#* (cd ../gc/$gcdir && $patch -p1 < ../$gc-android.patch > /dev/null)    */
-#* if [ $? != "0" ]; then echo "android patch failed"; exit 1; fi      */
+(cd "../gc/$gcdir"_fth && $patch -p1 < ../$gc-android.patch > /dev/null)
+if [ $? != "0" ]; then echo "android patch failed"; exit 1; fi
+(cd ../gc/$gcdir && $patch -p1 < ../$gc-android.patch > /dev/null)
+if [ $? != "0" ]; then echo "android patch failed"; exit 1; fi
 
 # general Bigloo patch
 (cd "../gc/$gc"_fth && $patch -p1 < ../$gc.patch > /dev/null)
