Yet another MinGW fix.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4,7 +4,7 @@
 #*    -------------------------------------------------------------    */
 #*    Author      :  Manuel Serrano                                    */
 #*    Creation    :  Tue Jan 25 16:05:10 1994                          */
-#*    Last change :  Mon Nov 23 11:47:30 2009 (serrano)                */
+#*    Last change :  Mon Nov 23 13:40:34 2009 (serrano)                */
 #*    Copyright   :  1994-2009 Manuel Serrano, see LICENSE file        */
 #*    -------------------------------------------------------------    */
 #*    The Bigloo configuration file                                    */
@@ -1323,6 +1323,16 @@ echo "* threadsupport=$threadsupport" >> $configurelog
 if [ "$threadsupport " = "no " ]; then
    pthreadlibs=no;
    gcthread=no;
+elif [ $hostos = "mingw" ]; then
+  # MinGW pre-test
+  if [ "$threadsupport " = " " ]; then
+     pthreadlibs=no;
+     gcthread=no;
+  else
+     echo "*** ERROR: MinGW does not support threads."
+     echo" Disable multithreading and re-configure."
+     exit 1
+  fi
 else
   # Does the system support threads
   if [ "$gcthread " = " "  ]; then
@@ -1352,13 +1362,6 @@ else
   else
     pthreaddecl=
     pthreadhastls=0
-  fi
-
-  if [ $hostos = "mingw" \
-       -a "$pthreadlibs" != "no" \
-       -a "$threadsupport " != "no " ]; then
-     extragclibs="$extragclibs $pthreadlibs"
-     extralibs="$extralibs $pthreadlibs"
   fi
 fi
 
