install and .afile (bootstrap)

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4,7 +4,7 @@
 #*    -------------------------------------------------------------    */
 #*    Author      :  Manuel Serrano                                    */
 #*    Creation    :  Tue Jan 25 16:05:10 1994                          */
-#*    Last change :  Wed Jun 21 10:29:50 2017 (serrano)                */
+#*    Last change :  Thu Jun 22 08:31:57 2017 (serrano)                */
 #*    Copyright   :  1994-2017 Manuel Serrano, see LICENSE file        */
 #*    -------------------------------------------------------------    */
 #*    The Bigloo configuration file                                    */
@@ -54,6 +54,8 @@ ccstyle=gcc
 cc=$CC  # left blank for default automatic configuration
 cflags=$CFLAGS
 lflags=$LDFLAGS
+lcustomflags=
+
 bigloo=$BIGLOO # used only for cross compiling
 if [ "$BFLAGS " != " " ]; then
   bflags=$BFLAGS;
@@ -2378,6 +2380,8 @@ if [ "$regexp " = " " ]; then
 	
       pcrelibs=yes
       extrapcre=pcre
+      libpcrebuildpath="\$(BOOTDIR)/pcre\$(LIBDIR)/\$(FILDIR)"
+      lcustomflags="-L$bootdir/pcre$libdir/$fildir $lcustomflags"
     else
       pcrelibs=no
     fi
@@ -2404,6 +2408,52 @@ if [ -f runtime/objs/obj_u/Unsafe/$regexp.c ]; then
 fi
 
 featureflags="-srfi enable-$regexp"
+
+#*---------------------------------------------------------------------*/
+#*    unistring                                                        */
+#*---------------------------------------------------------------------*/
+if [ "$customunistring" != "no" ]; then
+  haveunistring=1;
+  featureflags="-srfi enable-unistring $featureflags";
+  extraunistring=unistring
+  libunistringbuildpath="\$(BOOTDIR)/libunistring\$(LIBDIR)/\$(FILDIR)"
+  lcustomflags="-L$bootdir/libunistringlibdir/$fildir $lcustomflags"
+fi
+  
+if [ "$unistring " = " " -a "$customunistring " = "no " ]; then
+  extraunistring=`$autoconf unistring` || exit 1
+fi
+  
+if [ "$extraunistring " != "no " ]; then
+  if [ "$customunistring " != "no " ]; then
+    customunistring=yes
+    unistringversion=`echo $unistringsrc | sed 's/[^0-9]*//' | sed 's/[.][^0-9]*$//'`
+    
+    echo "+ Installing custom unistring source code."
+    (cd libunistring && UNISTRING=$unistringsrc && export UNISTRING && ./install-unistring) || exit 1
+
+    echo "+ Configuring custom unistring..."
+    (cd libunistring; . ./configure-unistring) || exit 1
+  fi
+  
+  unistringlibs=yes
+else
+  haveunistring=0;
+  extraunistring=no
+  if [ $unistringforce = "yes" ]; then
+    echo "*** ERROR:configure:--enable-unistring. Cannot find UNISTRING library."
+    echo "Aborting";
+    exit 1;
+  fi
+fi
+
+if [ "$extraunistring " != "no " ]; then
+  haveunistring=1;
+  featureflags="-srfi enable-unistring $featureflags";
+  extralibs="-l$extraunistring $extralibs"
+else
+  haveunistring=0;
+fi
 
 #*---------------------------------------------------------------------*/
 #*    avahi                                                            */
@@ -2699,48 +2749,6 @@ if [ $action = "all" -o $action = "bigloo_config" ]; then
     haveresolv=0;
     haveresolvapl=0;
     haveresolvzxfr=0;
-  fi
-
-  # Is unistring available?
-  if [ "$customunistring" != "no" ]; then
-    haveunistring=1;
-    featureflags="-srfi enable-unistring $featureflags";
-    extraunistring=unistring
-  fi
-  
-  if [ "$unistring " = " " -a "$customunistring " = "no " ]; then
-    extraunistring=`$autoconf unistring` || exit 1
-  fi
-  
-  if [ "$extraunistring " != "no " ]; then
-    if [ "$customunistring " != "no " ]; then
-      customunistring=yes
-      unistringversion=`echo $unistringsrc | sed 's/[^0-9]*//' | sed 's/[.][^0-9]*$//'`
-    
-      echo "+ Installing custom unistring source code."
-      (cd libunistring && UNISTRING=$unistringsrc && export UNISTRING && ./install-unistring) || exit 1
-
-      echo "+ Configuring custom unistring..."
-      (cd libunistring; . ./configure-unistring) || exit 1
-    fi
-	
-    unistringlibs=yes
-  else
-    haveunistring=0;
-    extraunistring=no
-    if [ $unistringforce = "yes" ]; then
-      echo "*** ERROR:configure:--enable-unistring. Cannot find UNISTRING library."
-      echo "Aborting";
-      exit 1;
-    fi
-  fi
-
-  if [ "$extraunistring " != "no " ]; then
-    haveunistring=1;
-    featureflags="-srfi enable-unistring $featureflags";
-    extralibs="-l$extraunistring $extralibs"
-  else
-    haveunistring=0;
   fi
 
   # Where to find the socket api
@@ -3251,7 +3259,7 @@ if [ $action = "all" -o $action = "bigloo_config" ]; then
               -e "s|@C_COMPILER_RPATH@|$crpath|" \
               -e "s|@C_STRIP_FLAGS@|$csflags|" \
               -e "s|@C_LINKER_STYLE@|$ldstyle|" \
-              -e "s|@C_LINKER_FLAGS@|$lflags|" \
+              -e "s|@C_LINKER_FLAGS@|$lflags $lcustomflags|" \
               -e "s|@C_LINKER_O_OPTION@|-o |" \
               -e "s|@C_LINKER_DEBUG_OPTION@|-g |" \
               -e "s|@C_LINKER_OPTIM_FLAGS@||" \
@@ -3688,8 +3696,8 @@ if [ $action = "all" -o $action = "Makefile.config" ]; then
   echo >> $makefile_cfg
 
   # additional bigloo compiler link flags (some architecture such as AIX
-  # require a special to link huge executable)
-  echo "EXTRA_LD_OPT=$lflags $rflags" >> $makefile_cfg
+  # require a special to link huge executable
+  echo "EXTRA_LD_OPT=$lflags $lcustomflags $rflags" >> $makefile_cfg
   if [ $sharedcompiler = "yes" ]; then
      echo "SHRD_COMP=yes" >> $makefile_cfg;
   else
@@ -3775,7 +3783,7 @@ if [ $action = "all" -o $action = "Makefile.config" ]; then
   if [ "$pcrelibs " != "no " ]; then
     if [ "$custompcre " = "yes " ]; then
       ldcompshared="-lpcre $ldcompshared" >> $makefile_cfg
-      ldcompstatic="\$(BOOTDIR)/pcre\$(LIBDIR)/\$(FILDIR)/libpcre.a $ldcompstatic" >> $makefile_cfg
+      ldcompstatic="$libpcrebuildpath/libpcre.a $ldcompstatic" >> $makefile_cfg
     else
       ldcompshared="-lpcre $ldcompshared" >> $makefile_cfg
       ldcompstatic="-lpcre $ldcompstatic" >> $makefile_cfg
@@ -3785,7 +3793,7 @@ if [ $action = "all" -o $action = "Makefile.config" ]; then
   if [ "$unistringlibs " != "no " ]; then
     if [ "$customunistring " = "yes " ]; then
       ldcompshared="-lunistring $ldcompshared" >> $makefile_cfg
-      ldcompstatic="\$(BOOTDIR)/libunistring\$(LIBDIR)/\$(FILDIR)/libunistring.a $ldcompstatic" >> $makefile_cfg
+      ldcompstatic="$libunistringbuildpath/libunistring.a $ldcompstatic" >> $makefile_cfg
     else
       ldcompshared="-lunistring $ldcompshared" >> $makefile_cfg
       ldcompstatic="-lunistring $ldcompstatic" >> $makefile_cfg
