Fix gmp autoconfiguration (bootstrap)

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4,7 +4,7 @@
 #*    -------------------------------------------------------------    */
 #*    Author      :  Manuel Serrano                                    */
 #*    Creation    :  Tue Jan 25 16:05:10 1994                          */
-#*    Last change :  Sun Sep 23 15:43:01 2018 (serrano)                */
+#*    Last change :  Tue Oct 23 13:12:51 2018 (serrano)                */
 #*    Copyright   :  1994-2018 Manuel Serrano, see LICENSE file        */
 #*    -------------------------------------------------------------    */
 #*    The Bigloo configuration file                                    */
@@ -2794,7 +2794,6 @@ if [ $action = "all" -o $action = "bigloo_config" ]; then
     havegmp=1;
     featureflags="-srfi enable-gmp $featureflags";
     extralibs="-lbigloogmp-$release $extralibs"
-    # buildgmplibdir=$buildlibdir/libuv/libuv-$libuvversion/lib/.libs
   elif [ "$gmpversion " = " " ]; then
     gmplib=`$autoconf bgl-pkg-config --libs gmp`;
 
@@ -2811,26 +2810,6 @@ if [ $action = "all" -o $action = "bigloo_config" ]; then
 	echo "Aborting";
  	exit 1;
       fi
-      if [ "$srfi27force " = "yes " ]; then
-	echo "*** ERROR:configure: Cannot find GMP library required by SRFI27."
-        echo "Please install GMP first or re-configure with \"--disable-srfi27\"."
-	echo "Aborting";
-	exit 1;
-      else
-        echo "*** WARNING:configure: Cannot find GMP library required by SRFI27."
-        echo "Disabling SRFI27."
-        napis=;
-        for a in $apis; do
-           if [ $a != "srfi27" ]; then
-             if [ "$napis " = " " ]; then
-               napis="$a";
-             else
-               napis="$napis $a";
-             fi
-           fi
-        done
-        apis=$napis;
-      fi
     else
       havegmp=1;
       featureflags="-srfi enable-gmp $featureflags";
@@ -2840,6 +2819,34 @@ if [ $action = "all" -o $action = "bigloo_config" ]; then
     havegmp=0;
   fi
 
+  if [ "$havegmp " = "0 " ]; then
+    if [ "$srfi27force " = "yes " ]; then
+      echo "*** ERROR:configure: Cannot find GMP library required by SRFI27."
+      echo "Please install GMP first or re-configure with \"--disable-srfi27\"."
+      echo "Aborting";
+      exit 1;
+    else
+      echo "*** WARNING:configure: Cannot find GMP library required by SRFI27."
+      echo "Disabling SRFI27."
+      napis=;
+      for a in $apis; do
+        if [ $a != "srfi27" ]; then
+          if [ "$napis " = " " ]; then
+            napis="$a";
+          else
+            napis="$napis $a";
+          fi
+        fi
+      done
+      apis=$napis;
+    fi
+    long_limbs=0;
+    longlong_limbs=0;
+  else
+    long_limbs=`$autoconf limbs --type="long" --cflags="-I$bootdir/lib/$release -L$bootdir/lib/$release"` || exit 1
+    longlong_limbs=`$autoconf limbs --type="$longlong" --cflags="-I$bootdir/lib/$release -L$bootdir/lib/$release"` || exit 1
+  fi
+    
   # Is resolv available?
   if [ "$resolv " = " " ]; then
     resolv=`$autoconf resolv` || exit 1
@@ -2961,9 +2968,6 @@ if [ $action = "all" -o $action = "bigloo_config" ]; then
       strtoull="bgl_strtoull"
     fi
   fi
-
-  long_limbs=`$autoconf limbs --type="long" --cflags="-I$bootdir/lib/$release -L$bootdir/lib/$release"` || exit 1
-  longlong_limbs=`$autoconf limbs --type="$longlong" --cflags="-I$bootdir/lib/$release -L$bootdir/lib/$release"` || exit 1
 
   long_sign_bit=`$autoconf signbit --type=long --alignment="$alignment"` || exit 1
   elong_sign_bit=`$autoconf signbit --type=long --alignment=0` || exit 1
