* bail out if we find an Android hostos but we can't determine which one it is.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -177,7 +177,7 @@ gstusethread=1
 customgc=yes
 gccustom=gc-7.2alpha4
 gcversion=
-# the following  variable is relevant only when using 
+# the following  variable is relevant only when using
 # standard (i.e. already existing and operational) Boehm's GC
 # and when customgc=no
 stdgclib=gc
@@ -365,7 +365,7 @@ while : ; do
 
     --bigloo_config.h)
       action="bigloo_config";;
-    
+
     --bigloo.h=*)
       action="bigloo_config";
       bigloo_h="`echo $1 | sed 's/^[^=]*=//'`";;
@@ -686,7 +686,7 @@ while : ; do
     --icc)
       if [ "$cc " = " " ]; then
         cc=icc;
-      fi; 
+      fi;
       as=icc;
       ldopt="no-share";
       coflags="$coflags -O3 -ip";
@@ -823,7 +823,7 @@ while : ; do
 
     --customgmp=yes|--customgmp)
       customgmp=yes;;
-      
+
     --customgmp=no)
       customgmp=no;;
 
@@ -1115,7 +1115,7 @@ done
 if [ $packrat_is_enabled = "yes" -a $srfi1_is_enabled = "no" ]; then
     echo "*** ERROR: packrat library requires srfi1."
     echo "Either disable packrat or enable srfi1."
-    echo 
+    echo
     echo "Enabled apis: $apis"
     exit 1
 fi
@@ -1123,7 +1123,7 @@ fi
 if [ $pkglib_is_enabled = "yes" -a $sqlite_is_enabled = "no" ]; then
     echo "*** ERROR: pkglib library requires sqlite."
     echo "Either disable pkglib or enable sqlite."
-    echo 
+    echo
     echo "Enabled apis: $apis"
     exit 1
 fi
@@ -1131,7 +1131,7 @@ fi
 if [ $fthread_is_enabled = "yes" -a $pthread_is_enabled = "no" ]; then
     echo "*** ERROR: fthread library requires pthread."
     echo "Either disable fthread or enable pthread."
-    echo 
+    echo
     echo "Enabled apis: $apis"
     exit 1
 fi
@@ -1179,11 +1179,11 @@ if [ "$cc " = " " ]; then
      if [ "$cc " != " " ]; then break; fi
   done
 
-  if [ "$cc " = " " ]; then 
+  if [ "$cc " = " " ]; then
     echo "Can't configure C compiler. Aborting (see configure.log)" >&2;
     exit 1;
   fi
-else  
+else
   ncc=`$autoconf cctest --cc="$cc"` || exit 1
   if [ "$ncc " != "$cc " ]; then
     echo "C compiler \"$cc\" broken. Aborting (see configure.log)" >&2;
@@ -1212,6 +1212,14 @@ if [ "$android " = "yes " ]; then
   hostos="android"
   hostcpu="arm"
   gcneedstackbase=1
+else
+  if [ "$hostos " = "android " ]; then
+    echo "*** ERROR: Android."
+    echo
+    echo "We detected an Android hostos, but we cannot determine the Android type"
+    echo "or the emulator is not running."
+    exit 1
+  fi
 fi
 
 #*---------------------------------------------------------------------*/
@@ -1273,7 +1281,7 @@ done
 if [ $action = "all" -o $action = "bigloo_config_el" ]; then
   # ld
   if [ "$ld " = " " ]; then ld=$cc; fi
-  
+
   # as
   if [ ! $as ]; then as="as"; fi
   as=`$autoconf ascpp --as="$as" --name=$name` || exit 1
@@ -1301,7 +1309,7 @@ if [ $action = "all" -o $action = "bigloo_config_el" ]; then
 
   if [ ! $strip ]; then strip="strip"; fi
   strip=`$autoconf strip --strip=$strip` || exit 1
-fi  
+fi
 
 #*---------------------------------------------------------------------*/
 #*    charset                                                          */
@@ -1440,14 +1448,14 @@ case $hostos in
         echo "*** WARNING:Can't find cygwindospath \"$cygwindospath\""
       fi
       cygwindospath=`echo "$cygwindospath" | sed -e 's/\\\\/\\\\\\\\/g'`
-  
+
       zipdir=`echo $zipdir | sed -e 's/\/cygdrive\/\([a-z]\)\//\1:\//'`
       zipdir=`echo $zipdir | sed -e "s/^\//$cygwindospath\\\\\\\\\\\\\\\\/"`
       zipdir=`echo $zipdir | sed -e 's/\//\\\\\\\\/g'`
       zipdir=`echo $zipdir | sed -e 's/\([^\\\\]\)\\\\\([^\\\\]\)/\1\\\\\\\\\2/g'`
       syszipdir=$zipdir
       syszipdirstr=`echo $syszipdir | sed -e 's|\\\\|\\\\\\\\|g'`
-  
+
       dlldir=`echo $dlldir | sed -e 's/\/cygdrive\/\([a-z]\)\//\1:\//'`
       dlldir=`echo $dlldir | sed -e "s/^\//$cygwindospath\\\\\\\\\\\\\\\\/"`
       dlldir=`echo $dlldir | sed -e 's/\//\\\\\\\\/g'`
@@ -1463,7 +1471,7 @@ case $hostos in
 
     if [ "$cygwindosjvm" = "yes" ]; then
       jshell="msdos"
-    fi 
+    fi
     if [ "$cygwindosdotnet" = "yes" ]; then
       dotnetshell="msdos"
     fi
@@ -1475,7 +1483,7 @@ case $hostos in
     ld="gcc"
     ldlibs=""
     ldcomplibs=""
-    ldflags="$ldflags -Wl,--enable-runtime-pseudo-reloc"  
+    ldflags="$ldflags -Wl,--enable-runtime-pseudo-reloc"
     ldopt=-shared
     havedlopen=1
     dlopen=""
@@ -1511,7 +1519,7 @@ case $hostos in
           echo "common parent directory. Please re-configure accordingly";
           exit 1;
         fi
-    
+
         ldinstallname="-install_name";
         ldinstallnamedirroot="Frameworks";
         sharedsuffix="dylib";
@@ -1569,8 +1577,8 @@ echo >> $configurelog
 #*---------------------------------------------------------------------*/
 echo "+ .NET specific configuration ($dotnetldstyle)..." >> $configurelog
 case $dotnetldstyle in
-  pnet|mono) 
-    ;;      
+  pnet|mono)
+    ;;
   *)
     echo "*** Don't know how to link .NET application [" $dotnetldstyl "]";
     exit 3;;
@@ -1702,13 +1710,13 @@ if [ "$mode" = "benchmark" ]; then
         coflags="$coflags -march=$hardtune -mcpu=$hardtune -mpreferred-stack-boundary=2 -fomit-frame-pointer -fschedule-insns2 -ffast-math";
       fi
       gcspecial=-DDONT_ADD_BYTE_AT_END;;
-        
+
     pentium3|pentium4)
       if [ "$ccprefix" = "gcc" ]; then
         coflags="$coflags -march=$hardtune -mpreferred-stack-boundary=2 -fomit-frame-pointer -fschedule-insns2 -ffast-math";
-      fi 
+      fi
       gcspecial="-DUSE_I686_PREFETCH -DDONT_ADD_BYTE_AT_END";;
-        
+
     athlon|athlon-mp|athlon-tbird|athlon-xp)
       if [ "$ccprefix" = "gcc" ]; then
         coflags="$coflags -march=$hardtune -mpreferred-stack-boundary=2 -fomit-frame-pointer -fschedule-insns2 -ffast-math";
@@ -1783,7 +1791,7 @@ if [ "$dubs_is_enabled " = "yes " ]; then
   if [ "$dbuslibs " != " " ]; then
     dbusld=`echo $dbuslibs | awk -F "@" '{ print $1 }'`
     dbusincl=`echo $dbuslibs | awk -F "@" '{ print $2 }'`
-  else 
+  else
     dbusld=""
     dbusincl=""
   fi
@@ -1941,7 +1949,7 @@ if [ $action = "all" -o $action = "bigloo_config" ]; then
     extralibs="-lbigloogmp-$release $extralibs"
   elif [ "$gmpversion " = " " ]; then
     gmpversion=`$autoconf gmp` || exit 1
-  
+
     if [ $gmpversion = "no" ]; then
       havegmp=0;
       if [ $gmpforce = "yes" ]; then
@@ -1981,7 +1989,7 @@ if [ $action = "all" -o $action = "bigloo_config" ]; then
   # Where to find the socket api
   socketlibs=`$autoconf socket --lib="$socketlibs"` || exit 1
   socklen=`$autoconf socklen --lib="$socketlibs"` || exit 1
- 
+
   if [ "$socketlibs " != " " ]; then
      extralibs="$socketlibs $extralibs"
   fi
@@ -2016,7 +2024,7 @@ if [ $action = "all" -o $action = "bigloo_config" ]; then
   # Does this system implement pipe?
   pipe=`$autoconf pipe` || exit 1
 
-  # Does this compiler implement labs? 
+  # Does this compiler implement labs?
   # llabs=`$autoconfdir/labs --user=$user --tmp=$buildtmp --cc="$cc"`
   # SE: fix, 27 oct 2006
   labs=`$autoconf labs` || exit 1
@@ -2077,22 +2085,22 @@ if [ $action = "all" -o $action = "bigloo_config" ]; then
 
   # Is sigchld available for us
   sigchld=`$autoconf sigchld` || exit 1
-  
+
   # Is sigaction available
   sigaction=`$autoconf sigaction` || exit 1
-  
+
   # Is select available
   select=`$autoconf select` || exit 1
-  
+
   # Is fcntl available
   fcntl=`$autoconf fcntl` || exit 1
-  
+
   # Is termio available
   termio=`$autoconf termio` || exit 1
-  
+
   # Is termio available
   termios=`$autoconf termios` || exit 1
-  
+
   # Does the system support posix-file-ops
   posixfileops=`$autoconf posixfileops` || exit 1
 
@@ -2142,7 +2150,7 @@ if [ $action = "all" -o $action = "bigloo_config" ]; then
   # shared link additional soname option
   if [ "$ldsoname" = "blank" ]; then
     ldsoname=""
-  else  
+  else
     ldsoname=`$autoconf ldsoname $libdir --ld="$ld" --soname="$ldsoname"` || exit 1
   fi
 
@@ -2320,14 +2328,14 @@ if [ $action = "all" -o $action = "bigloo_config" ]; then
       pathseparator=";"
       fileseparator="/"
       ostmp="$buildtmp"
-      staticlibsuf="a"    
+      staticlibsuf="a"
       ucs2displayable=0;;
 
     unknown)
       ostmp="/tmp"
       fileseparator="/"
       pathseparator=":"
-      staticlibsuf="a"    
+      staticlibsuf="a"
       ucs2displayable=0;;
 
     *)
@@ -2335,7 +2343,7 @@ if [ $action = "all" -o $action = "bigloo_config" ]; then
       pathseparator=":"
       fileseparator="/"
       ostmp="$buildtmp"
-      staticlibsuf="a"    
+      staticlibsuf="a"
       ucs2displayable=0;;
   esac
 
@@ -2534,7 +2542,7 @@ if [ $action = "all" -o $action = "bigloo_config_el" ]; then
   else
     emacsversion=`$autoconf emacsbrand --emacs=$emacs` || exit 1
   fi
-  
+
   if [ "$emacsversion" != "false" ]; then
     if [ "$lispdir " = " " ]; then
       emacslisppath=`$autoconf emacslisppath --emacs=$emacs` || exit 1
@@ -2557,7 +2565,7 @@ if [ $action = "all" -o $action = "bigloo_config_el" ]; then
   echo "(defvar bmacs-docdir \"$docdir\")" >> $bigloo_config_el
   echo "(defvar bmacs-lispdir \"$emacslisppath\")" >> $bigloo_config_el
 fi
-  
+
 
 #*---------------------------------------------------------------------*/
 #*    texinfo                                                          */
@@ -2840,12 +2848,12 @@ if [ $action = "all" -o $action = "Makefile.config" ]; then
   # Patch the code of the thread when using non custom GC
   if [ "$pthreadlibs" != "no" ]; then
     # the default gc on mingw is built with thread support.
-    # there is no need to link with a special version of gc library  
+    # there is no need to link with a special version of gc library
     if [ $isgccustom = "0" ]; then
       gclibth=$stdgclib
     else
       if [ "$hostos " = "mingw " ]; then
-        gclibth=bigloogc	
+        gclibth=bigloogc
       else
         gclibth=bigloogc_fth
       fi
@@ -2880,7 +2888,7 @@ if [ $action = "all" -o $action = "Makefile.config" ]; then
     cat api/ssl/src/Misc/ssl.init.in \
         | sed -e "s|@OPENSSLLIBS@|$openssllibs|g" \
         >>  lib/$release/ssl.init
- 
+
     dtls=1
     if [ "$openssldtls" = "no" ]; then
       dtls=0;
@@ -2913,7 +2921,7 @@ if [ $action = "all" -o $action = "Makefile.config" ]; then
     sqlitesrfi=sqlite;
     echo "SQLITESRFI=sqlite" >> $makefile_cfg
   fi
-    
+
   echo ";; automatically generated. Don't edit" >  lib/$release/sqlite.init
   cat api/sqlite/src/Misc/sqlite.init.in \
       | sed -e "s|@SQLITELIBS@|$sqlitelibs|g" \
@@ -2958,7 +2966,7 @@ if [ $action = "all" -o $action = "Makefile.config" ]; then
     echo "GSTREAMERLIBS=" >> $makefile_cfg
     echo "GSTREAMERFLAGS=" >> $makefile_cfg
   fi
-  
+
   # DBUS
   if [ "$dbusld " != " " ]; then
     echo ";; automatically generated. Don't edit" >  lib/$release/dbus.init
@@ -2980,7 +2988,7 @@ if [ $action = "all" -o $action = "Makefile.config" ]; then
     done
     apis=$napis;
   fi
-  
+
   # SCMPKG
   configure=api/pkgcomp/src/Llib/configure.scm
   rm -f $configure
@@ -3335,10 +3343,10 @@ echo "configuration completed" > config.status
 #*    Ok, we are done now                                              */
 #*---------------------------------------------------------------------*/
 if [ "$summary" = "yes" ]; then
-  echo 
-  echo 
+  echo
+  echo
   echo "** Configuration summary **"
-  echo 
+  echo
   echo "Release features:"
   echo "  release number.............. $release"
   echo "  supported backends.......... $bcke"
@@ -3369,7 +3377,7 @@ if [ "$summary" = "yes" ]; then
   echo "  bee support................. $bee"
   echo "  emacs....................... $emacs"
   echo "  emacs brand................. $emacsversion"
-  echo 
+  echo
   echo "Implementation details:"
   echo "  tuning...................... $mode $tuning"
   echo "  cc.......................... $cc"
