.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4,7 +4,7 @@
 #*    -------------------------------------------------------------    */
 #*    Author      :  Manuel Serrano                                    */
 #*    Creation    :  Tue Jan 25 16:05:10 1994                          */
-#*    Last change :  Mon Nov 23 18:18:40 2009 (serrano)                */
+#*    Last change :  Mon Nov 23 18:36:29 2009 (serrano)                */
 #*    Copyright   :  1994-2009 Manuel Serrano, see LICENSE file        */
 #*    -------------------------------------------------------------    */
 #*    The Bigloo configuration file                                    */
@@ -1069,10 +1069,12 @@ sqlite_is_enabled=no
 dbus_is_enabled=no
 fthread_is_enabled=no
 pthread_is_enabled=no
+srfi27_is_enabled=no
 
 for a in $apis; do
   case $a in
     srfi1) srfi1_is_enabled="yes";;
+    srfi27) srfi27_is_enabled="yes";;
     packrat) packrat_is_enabled="yes";;
     sqlite) sqlite_is_enabled="yes";;
     pkglib) pkglib_is_enabled="yes";;
@@ -1877,6 +1879,12 @@ if [ $action = "all" -o $action = "bigloo_config" ]; then
     havegmp=0;
     if [ $gmpforce = "yes" ]; then
 	echo "*** ERROR:configure:--enable-gmp. Cannot find GMP library."
+	echo "Aborting";
+	exit 1;
+    fi
+    if [ $srfi27_is_enable = "yes" ]; then
+	echo "*** ERROR:configure: Cannot find GMP library required by SRFI27."
+        echo "Please install GMP first or re-configure with --disable-srfi27."
 	echo "Aborting";
 	exit 1;
     fi
