Configure fixes

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,10 +1,10 @@
-#!/bin/sh
+!/bin/sh
 #*=====================================================================*/
 #*    serrano/prgm/project/bigloo/configure                            */
 #*    -------------------------------------------------------------    */
 #*    Author      :  Manuel Serrano                                    */
 #*    Creation    :  Tue Jan 25 16:05:10 1994                          */
-#*    Last change :  Tue Aug  4 19:25:31 2015 (serrano)                */
+#*    Last change :  Thu Sep  3 10:25:44 2015 (serrano)                */
 #*    Copyright   :  1994-2015 Manuel Serrano, see LICENSE file        */
 #*    -------------------------------------------------------------    */
 #*    The Bigloo configuration file                                    */
@@ -39,8 +39,8 @@ tmpdir=/tmp
 lispdir=
 
 #*--- api -------------------------------------------------------------*/
-importantapis="pthread fthread srfi18 ssl sqlite web multimedia mail calendar pkgcomp pkglib text srfi1 srfi27 packrat crypto openpgp wav avahi csv upnp libuv"
-apis="$importantapis gstreamer phidget alsa flac mpg123 phone"
+importantapis="pthread fthread srfi18 ssl sqlite web multimedia mail calendar pkgcomp pkglib text srfi1 srfi27 packrat crypto openpgp wav csv upnp libuv"
+apis="$importantapis gstreamer phidget alsa flac mpg123 phone avahi"
 
 #*--- bee configuration -----------------------------------------------*/
 bee=partial # "partial" or "full"
@@ -1076,7 +1076,7 @@ while : ; do
       echo "   --bigloo_config.jvm[=file]" >&2;
       echo "   --Makefile.config=file" >&2;
       echo "   --$configurelog=file" >&2;
-      echo "   --abort-missing (abort when as soon as a lib is missing)" >&2;
+      echo "   --abort-missing (abort as soon as a system lib is missing)" >&2;
       echo "   --no-summary" >&2;
       echo "   --bootconfig" >&2;
       echo "   --bootdir=dir" >&2;
@@ -4062,6 +4062,27 @@ if [ "$abortmissing " = "yes " ]; then
     if [ "$missing " != " " ]; then
 	echo ""
 	echo "*** ERROR Missing libraries: $missing" >&2
+	echo "exiting..." >&2
+	exit 1;
+    fi
+
+    if [ "$unistring " = "no " ]; then
+	echo ""
+	echo "*** ERROR Missing library: unistring" >&2
+	echo "exiting..." >&2
+	exit 1;
+    fi
+    
+    if [ ! "$regexp " = "pcre " ]; then
+	echo ""
+	echo "*** ERROR Missing library: pcre" >&2
+	echo "exiting..." >&2
+	exit 1;
+    fi
+    
+    if [ ! "$havegmp= " = "1 " ]; then
+	echo ""
+	echo "*** ERROR Missing library: gmp" >&2
 	echo "exiting..." >&2
 	exit 1;
     fi
