Integrate the CSV api

diff --git a/api/csv/src/Makefile b/api/csv/src/Makefile
--- a/api/csv/src/Makefile
+++ b/api/csv/src/Makefile
@@ -1,15 +1,15 @@
 #*=====================================================================*/
-#*    serrano/prgm/project/bigloo/api/web/src/Makefile                 */
+#*    serrano/prgm/project/bigloo/api/csv/src/Makefile                 */
 #*    -------------------------------------------------------------    */
 #*    Author      :  Manuel Serrano                                    */
 #*    Creation    :  Wed Apr  1 18:45:46 1998                          */
-#*    Last change :  Tue Feb 21 07:19:48 2012 (serrano)                */
+#*    Last change :  Thu Feb 23 18:59:53 2012 (serrano)                */
 #*    -------------------------------------------------------------    */
 #*    The makefile to build the library.                               */
 #*=====================================================================*/
 
 #*---------------------------------------------------------------------*/
-#*    Standard Web configuration                                       */
+#*    Standard Csv configuration                                       */
 #*---------------------------------------------------------------------*/
 include ../../../Makefile.config
 include ../../../Makefile.misc
@@ -18,11 +18,11 @@ include ../../../Makefile.misc
 #*    Compilers, Tools and Destinations                                */
 #*---------------------------------------------------------------------*/
 # the library name
-API		= web
+API		= csv
 # Directories
 BIGLOO_SRC_DIR 	= Llib
-JAVA_SRC_DIR 	= Java
-C_SRC_DIR 	= Posix
+C_SRC_DIR 	= Clib
+PLUGIN_SRC_DIR 	= Plugin
 MISC_SRC_DIR 	= Misc
 # Where to store the library class files
 PBASE		= bigloo.$(API)
@@ -34,35 +34,66 @@ AFILE		= $(BGLBUILDBINDIR)/$(AFILE_EXE)
 JFILE		= $(BGLBUILDBINDIR)/$(JFILE_EXE)
 DEPEND		= $(BGLBUILDBINDIR)/$(BDEPEND_EXE)
 BTAGS		= $(BGLBUILDBINDIR)/$(BTAGS_EXE)
+BTAGS		= $(BGLBUILDBINDIR)/$(BTAGS_EXE)
+CIGLOO		= $(BGLBUILDBINDIR)/cigloo
 # Bigloo compilation options
-BAPIFLAGS	= $(BFLAGS) -I Llib -lib-dir $(BOOTLIBDIR) -unsafe -safee
+BAPIFLAGS	= $(BFLAGS) -I Llib -lib-dir $(BOOTLIBDIR) -unsafe -safee \
+                  -srfi $(API) -copt "$(CSVCFLAGS)"
+CAPIFLAGS       = $(CSVCFLAGS) $(CGCTHREADFLAGS)
 # Flags to build a heap
 BHEAPFLAGS	= -unsafe -q -mkaddheap -mkaddlib -L $(BOOTLIBDIR) -I Llib \
-                  -heap-library $(API)
+                  -heap-library $(API) -srfi $(API)
+# C flags
+CEFLAGS		= $(CSVCFLAGS)
+
+# Additional pthread lib for C
+ifeq "$(CSVLIBS) " " "
+EXTRALIBS	= 
+else
+EXTRALIBS	= $(CSVLIBS)
+endif
 
 #*---------------------------------------------------------------------*/
 #*    Scheme extended objects                                          */
 #*---------------------------------------------------------------------*/
-_BGL_OBJECTS	= xml css css_ast css_lexer css_parser cgi rss atom feeds \
-                  html webdav date
+_BGL_OBJECTS	= csv
 
-_OBJECTS	= $(_BGL_OBJECTS)
+ifeq "$(CSVLIBS) " " "
+_C_OBJECTS	= 
+else
+_C_OBJECTS	= 
+endif
+_JAVA_CLASSES	= 
+
+_OBJECTS	= $(_C_OBJECTS) $(_BGL_OBJECTS)
 OBJECTS		= $(_OBJECTS:%=objs/%.o)
+
 EOBJECTS	= objs/make_lib.o
 
-BGL_CLASSES	= $(_OBJECTS:%=$(CLASS_DIR)/%.class)
+BGL_CLASSES	= $(_BGL_OBJECTS:%=$(CLASS_DIR)/%.class)
 BGL_ECLASSES	= $(CLASS_EDIR)/make_lib.class
 
-_BGL_SOURCES	= $(_BGL_OBJECTS:%=$(BIGLOO_SRC_DIR)/%.scm)
+JAVA_CLASSES	= $(_JAVA_CLASSES:%=$(CLASS_DIR)/%.class)
+JAVA_CLASSES_SRC= $(_JAVA_CLASSES:%=$(CLASS_DIR)/%.java)
 
-SOURCES		= $(_BGL_SOURCES)
- 
+_WIN32_SRC	= 
+
+_BGL_SOURCES	= $(_BGL_OBJECTS:%=$(BIGLOO_SRC_DIR)/%.scm)
+_C_SOURCES	= $(_C_OBJECTS:%=$(C_SRC_DIR)/%.c)
+_JAVA_SOURCES	= $(_JAVA_CLASSES:%=$(JAVA_SRC_DIR)/%.java)
+_WIN32_SOURCES	= $(_WIN32_SRC:%=$(WIN32_SRC_DIR)/%)
+
+SOURCES		= $(_BGL_SOURCES) \
+                  $(_C_SOURCES) \
+                  $(_JAVA_SOURCES)
+INCLUDES	= 
+
 #*---------------------------------------------------------------------*/
 #*    Sources                                                          */
 #*---------------------------------------------------------------------*/
-POPULATION	= $(SOURCES) \
-                  $(MISC_SRC_DIR)/make_lib.scm \
-                  $(MISC_SRC_DIR)/$(API).init \
+POPULATION	= $(SOURCES) $(INCLUDES) $(_WIN32_SOURCES) \
+		  $(MISC_SRC_DIR)/make_lib.scm \
+                  $(MISC_SRC_DIR)/$(API).init.in \
                   Makefile
 
 #*---------------------------------------------------------------------*/
@@ -70,19 +101,21 @@ POPULATION	= $(SOURCES) \
 #*---------------------------------------------------------------------*/
 .PHONY: c jvm build-c build-jvm
 
-all:
+all: 
 	@ if [ "$(NATIVEBACKEND)" = "yes" ]; then \
              $(MAKE) build-c; \
-	  fi
-	@ if [ "$(JVMBACKEND)" = "yes" ]; then \
-             $(MAKE) build-jvm; \
 	  fi
 
 c: build-c
 build-c: api-c
 
 jvm: build-jvm
-build-jvm: api-jvm
+build-jvm:
+
+$(MISC_SRC_DIR)/$(API).init: $(MISC_SRC_DIR)/$(API).init.in
+	@ echo "*** ERROR: $@ is out of date (older than $?)"
+	@ echo "You need to re-configure \"(cd ..; ./configure --bootconfig)\""
+	@ exit 1
 
 #*---------------------------------------------------------------------*/
 #*    pop ...                                                          */
@@ -94,6 +127,9 @@ pop:
 #*    clean                                                            */
 #*---------------------------------------------------------------------*/
 clean: api-clean
+	/bin/rm -f $(C_SRC_DIR)/bglpcm.h
+	/bin/rm -f $(C_SRC_DIR)/bglctl.h
+	/bin/rm -f $(C_SRC_DIR)/bglmixer.h
 
 cleanall: api-cleanall
 
@@ -103,3 +139,11 @@ distclean: cleanall
 #*    Common API rules                                                 */
 #*---------------------------------------------------------------------*/
 include ../../Makefile.api
+
+#bdepend start (don't edit)
+#*---------------------------------------------------------------------*/
+#*    Dependencies ...                                                 */
+#*---------------------------------------------------------------------*/
+objs/csv.o Llib/csv.class:
+
+#bdepend stop
